FROM node:lts-alpine AS build
WORKDIR /app
COPY ./frontend/. .
COPY stack.env .
RUN npm i &&\
    source stack.env &&\
    npm run build -- --mode production &&\
    npm i --omit=dev --ignore-scripts

FROM node:lts-alpine
USER node:node
WORKDIR /app
COPY --from=build --chown=node:node /app/build ./build
COPY --from=build --chown=node:node /app/node_modules ./node_modules
COPY --from=build --chown=node:node /app/package.json .
CMD ["node", "./build"]
